---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immunoplex-batch-cal-worker
  labels:
    app: immunoplex-batch-cal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immunoplex-batch-cal-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: immunoplex-batch-cal-worker
    spec:
      containers:
        - image: ghcr.io/immunoplex/immunoplex-batch-cal-worker:main
          imagePullPolicy: Always
          name: immunoplex-batch-cal-worker
          env:
            # Redis
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_AUTH
            - name: REDIS_DB
              value: "0"
            # PostgreSQL
            - name: DB_NAME
              value: "immunoodle"
            - name: DB_HOST
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: DB_SSLMODE
              value: "disable"
            # Output
            - name: OUTPUT_DIR
              value: "/data/bayes"
            - name: PROGRESS_DIR
              value: "/tmp"
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "8"
              memory: "16Gi"
