---
apiVersion: v1
kind: Service
metadata:
  name: immunoplex-batch-cal-api
  labels:
    app: immunoplex-batch-cal-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
  selector:
    app: immunoplex-batch-cal-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immunoplex-batch-cal-api
  labels:
    app: immunoplex-batch-cal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immunoplex-batch-cal-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: immunoplex-batch-cal-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - image: ghcr.io/immunoplex/immunoplex-batch-cal-api:main
          imagePullPolicy: Always
          name: immunoplex-batch-cal-api
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: madi
                  key: REDIS_AUTH
            - name: REDIS_DB
              value: "0"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: madi
                  key: API_KEY
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
